### ISSUE TITLE
sed command broken for windows and linux users

### ISSUE THREAD

**Issue by eversC** [DataDog/TrainingEnvironment#2]
https://github.com/DataDog/TrainingEnvironment/blob/5e818ff6222e361b12176711f7a45636c06f5a2c/Datadog101/install.sh#L35

Removing the quotes from `sed -i "" ....` fixed it.

**Comment by eversC** [comment]
note: this works fine on a mac, with the quotes.

Removing the quotes from the script, and re-running on a mac, fails with `sed: 1: "Vagrantfile": invalid command code V`

**Comment by technovangelist** [comment]
I basically did what you suggested, but added a case switch to look for which OS you are using. Thanks for pointing me in the right direction
